import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { TokenListProvider } from '@/context/tokensContext';
import { Toaster } from 'react-hot-toast';
import LanguageSwitcher from './components/LanguageSwitcher';
import { NextIntlClientProvider } from 'next-intl';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  let locale = 'en';
  const messages = (await import(`../messages/${locale}.json`)).default;

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <LanguageSwitcher />
          <TokenListProvider>
            {children}
            <Toaster position='bottom-right' />
          </TokenListProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
